/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/users/day": {
    get: operations["getDay"];
    put: operations["addProductToDay"];
    post: operations["createUserDay"];
  };
  "/api/v1/product": {
    get: operations["getProductById"];
    put: operations["updateProduct"];
    post: operations["createProduct"];
  };
  "/api/v1/auth/register": {
    post: operations["register"];
  };
  "/api/v1/auth/authenticate": {
    post: operations["authenticate"];
  };
  "/api/v1/user": {
    get: operations["getUserInfo"];
  };
  "/api/v1/product/all": {
    get: operations["getAllProducts"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CustomProduct: {
      name: string;
      protein: string;
      carbs: string;
      fat: string;
      sugar: string;
    };
    GrantedAuthority: {
      authority: string;
    };
    User: {
      /** Format: uuid */
      id: string;
      lastname: string;
      firstname: string;
      email: string;
      password: string;
      /** @enum {string} */
      role: "USER" | "ADMIN";
      enabled: boolean;
      authorities: components["schemas"]["GrantedAuthority"][];
      username: string;
      credentialsNonExpired: boolean;
      accountNonLocked: boolean;
      accountNonExpired: boolean;
    };
    UserDay: {
      /** Format: int32 */
      id: number;
      user: components["schemas"]["User"];
      /** Format: date */
      date: string;
      breakfastProducts: components["schemas"]["CustomProduct"][];
      lunchProducts: components["schemas"]["CustomProduct"][];
    };
    Product: {
      /** Format: int64 */
      id: number;
      name: string;
      protein: string;
      carbs: string;
      fat: string;
      sugar: string;
    };
    RegisterRequest: {
      firstname: string;
      lastname: string;
      email: string;
      password: string;
    };
    AuthenticationResponse: {
      token: string;
    };
    AuthenticationRequest: {
      email: string;
      password: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  getDay: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDay"];
        };
      };
    };
  };
  addProductToDay: {
    parameters: {
      query: {
        userDayId: number;
        dayTime: "BREAKFAST" | "LUNCH";
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomProduct"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDay"];
        };
      };
    };
  };
  createUserDay: {
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDay"];
        };
      };
    };
  };
  getProductById: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Product"];
        };
      };
    };
  };
  updateProduct: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Product"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Product"];
        };
      };
    };
  };
  createProduct: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Product"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Product"];
        };
      };
    };
  };
  register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthenticationResponse"];
        };
      };
    };
  };
  authenticate: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthenticationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthenticationResponse"];
        };
      };
    };
  };
  getUserInfo: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
  };
  getAllProducts: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Product"][];
        };
      };
    };
  };
}
