name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: ENV=prod npm run build

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.pkg.github.com/veccv/fit-app-v5-front/fitappfront:0.0.1 .
          docker push docker.pkg.github.com/veccv/fit-app-v5-front/fitappfront:0.0.1